const mongoose = require('mongoose');
require('dotenv').config();
const Pais = require('../models/pais');

const paisesData = [
    { code: 'AF', pais: 'Afganistán' },
    { code: 'AL', pais: 'Albania' },
    { code: 'DE', pais: 'Alemania' },
    { code: 'AD', pais: 'Andorra' },
    { code: 'AO', pais: 'Angola' },
    { code: 'AI', pais: 'Anguila' },
    { code: 'AQ', pais: 'Antártida' },
    { code: 'AG', pais: 'Antigua y Barbuda' },
    { code: 'SA', pais: 'Arabia Saudita' },
    { code: 'DZ', pais: 'Argelia' },
    { code: 'AR', pais: 'Argentina' },
    { code: 'AM', pais: 'Armenia' },
    { code: 'AW', pais: 'Aruba' },
    { code: 'AU', pais: 'Australia' },
    { code: 'AT', pais: 'Austria' },
    { code: 'AZ', pais: 'Azerbaiyán' },
    { code: 'BS', pais: 'Bahamas' },
    { code: 'BD', pais: 'Bangladés' },
    { code: 'BB', pais: 'Barbados' },
    { code: 'BH', pais: 'Baréin' },
    { code: 'BE', pais: 'Bélgica' },
    { code: 'BZ', pais: 'Belice' },
    { code: 'BJ', pais: 'Benín' },
    { code: 'BM', pais: 'Bermudas' },
    { code: 'BY', pais: 'Bielorrusia' },
    { code: 'BO', pais: 'Bolivia' },
    { code: 'BA', pais: 'Bosnia y Herzegovina' },
    { code: 'BW', pais: 'Botsuana' },
    { code: 'BR', pais: 'Brasil' },
    { code: 'BN', pais: 'Brunéi' },
    { code: 'BG', pais: 'Bulgaria' },
    { code: 'BF', pais: 'Burkina Faso' },
    { code: 'BI', pais: 'Burundi' },
    { code: 'BT', pais: 'Bután' },
    { code: 'CV', pais: 'Cabo Verde' },
    { code: 'KH', pais: 'Camboya' },
    { code: 'CM', pais: 'Camerún' },
    { code: 'CA', pais: 'Canadá' },
    { code: 'TD', pais: 'Chad' },
    { code: 'CL', pais: 'Chile' },
    { code: 'CN', pais: 'China' },
    { code: 'CY', pais: 'Chipre' },
    { code: 'CO', pais: 'Colombia' },
    { code: 'KM', pais: 'Comoras' },
    { code: 'CG', pais: 'Congo' },
    { code: 'KR', pais: 'Corea del Sur' },
    { code: 'CR', pais: 'Costa Rica' },
    { code: 'CI', pais: 'Costa de Marfil' },
    { code: 'HR', pais: 'Croacia' },
    { code: 'CU', pais: 'Cuba' },
    { code: 'CW', pais: 'Curazao' },
    { code: 'DK', pais: 'Dinamarca' },
    { code: 'DM', pais: 'Dominica' },
    { code: 'EC', pais: 'Ecuador' },
    { code: 'EG', pais: 'Egipto' },
    { code: 'SV', pais: 'El Salvador' },
    { code: 'AE', pais: 'Emiratos Árabes Unidos' },
    { code: 'ER', pais: 'Eritrea' },
    { code: 'SK', pais: 'Eslovaquia' },
    { code: 'SI', pais: 'Eslovenia' },
    { code: 'ES', pais: 'España' },
    { code: 'US', pais: 'Estados Unidos' },
    { code: 'EE', pais: 'Estonia' },
    { code: 'ET', pais: 'Etiopía' },
    { code: 'FJ', pais: 'Fiyi' },
    { code: 'PH', pais: 'Filipinas' },
    { code: 'FI', pais: 'Finlandia' },
    { code: 'FR', pais: 'Francia' },
    { code: 'GA', pais: 'Gabón' },
    { code: 'GM', pais: 'Gambia' },
    { code: 'GE', pais: 'Georgia' },
    { code: 'GH', pais: 'Ghana' },
    { code: 'GI', pais: 'Gibraltar' },
    { code: 'GR', pais: 'Grecia' },
    { code: 'GD', pais: 'Granada' },
    { code: 'GL', pais: 'Groenlandia' },
    { code: 'GP', pais: 'Guadalupe' },
    { code: 'GU', pais: 'Guam' },
    { code: 'GT', pais: 'Guatemala' },
    { code: 'GY', pais: 'Guyana' },
    { code: 'GF', pais: 'Guayana Francesa' },
    { code: 'GN', pais: 'Guinea' },
    { code: 'GQ', pais: 'Guinea Ecuatorial' },
    { code: 'GW', pais: 'Guinea-Bisáu' },
    { code: 'HT', pais: 'Haití' },
    { code: 'HN', pais: 'Honduras' },
    { code: 'HK', pais: 'Hong Kong' },
    { code: 'HU', pais: 'Hungría' },
    { code: 'IN', pais: 'India' },
    { code: 'ID', pais: 'Indonesia' },
    { code: 'IR', pais: 'Irán' },
    { code: 'IQ', pais: 'Irak' },
    { code: 'IE', pais: 'Irlanda' },
    { code: 'BV', pais: 'Isla Bouvet' },
    { code: 'CX', pais: 'Isla de Navidad' },
    { code: 'IS', pais: 'Islandia' },
    { code: 'KY', pais: 'Islas Caimán' },
    { code: 'CC', pais: 'Islas Cocos' },
    { code: 'CK', pais: 'Islas Cook' },
    { code: 'FO', pais: 'Islas Feroe' },
    { code: 'HM', pais: 'Islas Heard y McDonald' },
    { code: 'FK', pais: 'Islas Malvinas' },
    { code: 'MP', pais: 'Islas Marianas del Norte' },
    { code: 'MH', pais: 'Islas Marshall' },
    { code: 'UM', pais: 'Islas menores alejadas de EE.UU.' },
    { code: 'PN', pais: 'Islas Pitcairn' },
    { code: 'SB', pais: 'Islas Salomón' },
    { code: 'TC', pais: 'Islas Turcas y Caicos' },
    { code: 'VG', pais: 'Islas Vírgenes Británicas' },
    { code: 'VI', pais: 'Islas Vírgenes de EE.UU.' },
    { code: 'IL', pais: 'Israel' },
    { code: 'IT', pais: 'Italia' },
    { code: 'JM', pais: 'Jamaica' },
    { code: 'JP', pais: 'Japón' },
    { code: 'JE', pais: 'Jersey' },
    { code: 'JO', pais: 'Jordania' },
    { code: 'KZ', pais: 'Kazajistán' },
    { code: 'KE', pais: 'Kenia' },
    { code: 'KG', pais: 'Kirguistán' },
    { code: 'KI', pais: 'Kiribati' },
    { code: 'KW', pais: 'Kuwait' },
    { code: 'LA', pais: 'Laos' },
    { code: 'LS', pais: 'Lesoto' },
    { code: 'LV', pais: 'Letonia' },
    { code: 'LB', pais: 'Líbano' },
    { code: 'LR', pais: 'Liberia' },
    { code: 'LY', pais: 'Libia' },
    { code: 'LI', pais: 'Liechtenstein' },
    { code: 'LT', pais: 'Lituania' },
    { code: 'LU', pais: 'Luxemburgo' },
    { code: 'MO', pais: 'Macao' },
    { code: 'MK', pais: 'Macedonia del Norte' },
    { code: 'MG', pais: 'Madagascar' },
    { code: 'MY', pais: 'Malasia' },
    { code: 'MW', pais: 'Malaui' },
    { code: 'MV', pais: 'Maldivas' },
    { code: 'ML', pais: 'Malí' },
    { code: 'MT', pais: 'Malta' },
    { code: 'MA', pais: 'Marruecos' },
    { code: 'MQ', pais: 'Martinica' },
    { code: 'MU', pais: 'Mauricio' },
    { code: 'MR', pais: 'Mauritania' },
    { code: 'YT', pais: 'Mayotte' },
    { code: 'MX', pais: 'México' },
    { code: 'FM', pais: 'Micronesia' },
    { code: 'MD', pais: 'Moldavia' },
    { code: 'MC', pais: 'Mónaco' },
    { code: 'MN', pais: 'Mongolia' },
    { code: 'ME', pais: 'Montenegro' },
    { code: 'MS', pais: 'Montserrat' },
    { code: 'MZ', pais: 'Mozambique' },
    { code: 'MM', pais: 'Myanmar' },
    { code: 'NA', pais: 'Namibia' },
    { code: 'NR', pais: 'Nauru' },
    { code: 'NP', pais: 'Nepal' },
    { code: 'NI', pais: 'Nicaragua' },
    { code: 'NE', pais: 'Níger' },
    { code: 'NG', pais: 'Nigeria' },
    { code: 'NU', pais: 'Niue' },
    { code: 'NF', pais: 'Norfolk' },
    { code: 'NO', pais: 'Noruega' },
    { code: 'NC', pais: 'Nueva Caledonia' },
    { code: 'NZ', pais: 'Nueva Zelanda' },
    { code: 'OM', pais: 'Omán' },
    { code: 'NL', pais: 'Países Bajos' },
    { code: 'PK', pais: 'Pakistán' },
    { code: 'PW', pais: 'Palaos' },
    { code: 'PA', pais: 'Panamá' },
    { code: 'PG', pais: 'Papúa Nueva Guinea' },
    { code: 'PY', pais: 'Paraguay' },
    { code: 'PE', pais: 'Perú' },
    { code: 'PF', pais: 'Polinesia Francesa' },
    { code: 'PL', pais: 'Polonia' },
    { code: 'PT', pais: 'Portugal' },
    { code: 'PR', pais: 'Puerto Rico' },
    { code: 'QA', pais: 'Catar' },
    { code: 'GB', pais: 'Reino Unido' },
    { code: 'RE', pais: 'Reunión' },
    { code: 'RW', pais: 'Ruanda' },
    { code: 'RO', pais: 'Rumania' },
    { code: 'RU', pais: 'Rusia' },
    { code: 'EH', pais: 'Sáhara Occidental' },
    { code: 'WS', pais: 'Samoa' },
    { code: 'AS', pais: 'Samoa Americana' },
    { code: 'SM', pais: 'San Marino' },
    { code: 'SH', pais: 'Santa Elena' },
    { code: 'LC', pais: 'Santa Lucía' },
    { code: 'ST', pais: 'Santo Tomé y Príncipe' },
    { code: 'SN', pais: 'Senegal' },
    { code: 'RS', pais: 'Serbia' },
    { code: 'SC', pais: 'Seychelles' },
    { code: 'SL', pais: 'Sierra Leona' },
    { code: 'SG', pais: 'Singapur' },
    { code: 'SX', pais: 'Sint Maarten' },
    { code: 'SY', pais: 'Siria' },
    { code: 'SO', pais: 'Somalia' },
    { code: 'LK', pais: 'Sri Lanka' },
    { code: 'SZ', pais: 'Suazilandia' },
    { code: 'ZA', pais: 'Sudáfrica' },
    { code: 'SD', pais: 'Sudán' },
    { code: 'SS', pais: 'Sudán del Sur' },
    { code: 'SE', pais: 'Suecia' },
    { code: 'CH', pais: 'Suiza' },
    { code: 'SR', pais: 'Surinam' },
    { code: 'SJ', pais: 'Svalbard y Jan Mayen' },
    { code: 'TH', pais: 'Tailandia' },
    { code: 'TW', pais: 'Taiwán' },
    { code: 'TZ', pais: 'Tanzania' },
    { code: 'TJ', pais: 'Tayikistán' },
    { code: 'IO', pais: 'Territorio Británico del Océano Índico' },
    { code: 'TF', pais: 'Territorios Australes Franceses' },
    { code: 'TL', pais: 'Timor Oriental' },
    { code: 'TG', pais: 'Togo' },
    { code: 'TK', pais: 'Tokelau' },
    { code: 'TO', pais: 'Tonga' },
    { code: 'TT', pais: 'Trinidad y Tobago' },
    { code: 'TN', pais: 'Túnez' },
    { code: 'TM', pais: 'Turkmenistán' },
    { code: 'TR', pais: 'Turquía' },
    { code: 'TV', pais: 'Tuvalu' },
    { code: 'UA', pais: 'Ucrania' },
    { code: 'UG', pais: 'Uganda' },
    { code: 'UY', pais: 'Uruguay' },
    { code: 'UZ', pais: 'Uzbekistán' },
    { code: 'VU', pais: 'Vanuatu' },
    { code: 'VA', pais: 'Vaticano' },
    { code: 'VE', pais: 'Venezuela' },
    { code: 'VN', pais: 'Vietnam' },
    { code: 'WF', pais: 'Wallis y Futuna' },
    { code: 'YE', pais: 'Yemen' },
    { code: 'DJ', pais: 'Yibuti' },
    { code: 'ZM', pais: 'Zambia' },
    { code: 'ZW', pais: 'Zimbabue' }
];

const seedPaises = async () => {
    try {
        // Conectar a la base de datos
        await mongoose.connect(process.env.DB_MONGO);
        console.log('Conectado a la base de datos');

        // Eliminar países existentes
        await Pais.deleteMany({});
        console.log('Países eliminados');

        // Insertar nuevos países
        await Pais.insertMany(paisesData);
        console.log('Países insertados correctamente');

        mongoose.connection.close();
        console.log('Conexión cerrada');
    } catch (error) {
        console.error('Error al ejecutar el seeder:', error);
        process.exit(1);
    }
};

seedPaises();

